In [1]:
import numpy as np 

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a= [1,2,3,43]
a 

[1, 2, 3, 43]

In [7]:
a = [1,2,3,4.5,"hello"]
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [10]:
l=[[1,2,3,4], [5,6,7,8],[9,10,11,12]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [11]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.array([1,12,2])
arr

array([ 1, 12,  2])

In [16]:
arr = np.arange(1,12,2)
arr

array([ 1,  3,  5,  7,  9, 11])

In [17]:
arr = np.zeros([6])
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros([6,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
import numpy as np 

arr = np.linspace(1,5,2)
arr



array([1., 5.])

In [10]:
np.random.rand(5)

array([0.57921269, 0.38726978, 0.28578973, 0.95674727, 0.12965534])

In [12]:
np.random.randn(10)


array([ 0.61063931,  1.14096515, -1.02627971, -0.44988357,  2.58258516,
       -2.30777882,  0.91018091, -0.30767956,  0.88685964, -1.34911274])

In [15]:
np.random.randint(1,100,5)

array([59, 98, 80, 34, 14], dtype=int32)

In [17]:
arr = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr.min()

np.int64(1)

In [22]:
arr = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
np.min(arr)

np.int64(1)

In [24]:
arr.max()

np.int64(8)

In [25]:
arr.sum()

np.int64(39)

In [26]:
np.sum(arr,axis=0)

array([10, 13, 16])

In [28]:
np.sum(arr,axis=1)

array([ 6, 12, 21])

In [29]:
arr.mean()

np.float64(4.333333333333333)

In [30]:
arr.argmax()

np.int64(8)

In [31]:
arr.argmin()

np.int64(0)

In [32]:
arr.std()

np.float64(2.211083193570267)

In [33]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])