In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

np.int64(9)

In [4]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [5]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[3::3]

array([ 4,  7, 10])

In [10]:
arr=np.arange(1,31).reshape(6,5)A
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[1,1]

np.int64(7)

In [14]:
arr[0,4]

np.int64(5)

In [5]:
import numpy as np

In [9]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5,4]

np.int64(30)

In [11]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [13]:
arr

array([], shape=(1, 0), dtype=int64)

In [15]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

In [18]:
arr[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25],
       [27, 28, 29, 30]])

In [20]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [22]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])