In [ ]:
# Arithmatic operation 

In [2]:
import numpy as np 



In [7]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

arr1= a1 +a2
arr1

array([ 7,  9, 11, 13, 15])

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
arr2= a2 -a1
arr2


array([5, 5, 5, 5, 5])

In [9]:
arr3 = a1*a2
arr3

array([ 6, 14, 24, 36, 50])

In [11]:
arr4  = a1/a2
arr4

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
arr5 = a1//a2
arr5

array([0, 0, 0, 0, 0])

In [14]:
arr6 = a2%a1
arr6

array([0, 1, 2, 1, 0])

In [15]:
arr7 = a1 **a2
arr7

array([      1,     128,    6561,  262144, 9765625])

In [16]:
# broadcasting 


In [17]:
import numpy as np

In [21]:
l = [10,20,30,40]
arr = np.array(l)

In [22]:
arr+10

array([20, 30, 40, 50])

In [23]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [25]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice =a[:5]
slice

array([1, 2, 3, 4, 5])

In [28]:
slice =slice*10
slice

array([10, 20, 30, 40, 50])

In [32]:
a[4:6]*20

array([100, 120])

In [33]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
a 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
b = a
b


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
b[0]=10
b

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [43]:
b

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [44]:
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
# matrix operation 


In [45]:
import numpy as np 


In [48]:
A = np.array([[1,2],[3,4]])
B =np.array([[5,6],[7,8]])

A

array([[1, 2],
       [3, 4]])

In [49]:
B

array([[5, 6],
       [7, 8]])

In [50]:
A@B

array([[19, 22],
       [43, 50]])

In [51]:
# Transport 


In [52]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
# stacking

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [54]:
np.vstack((arr1,arr2))

array([[ 7,  9, 11, 13, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])