In [ ]:
# valid soduko 

In [1]:
import numpy as np

s= np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [2]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
a = np.sum(s,axis=0)
a 

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
a = np.sum(s,axis=1)
a

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [9]:
for i in range(0,9,3):
    for j in range (0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


In [8]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [10]:
import numpy as np 

In [12]:
data =np.array([
    [18, 85 ,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
    ])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [14]:
# get the shape of matrix

(5, 3)

In [28]:
data.shape

(5, 3)

In [29]:
# FIND THE AVERAGE marks 

np.mean(data[:,0])

np.float64(18.4)

In [30]:
# extacrt the math marks of all student 
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
# find the highest science marks

In [31]:
np.max(data[:,2])

np.int64(95)